skip_commits:
  message: /((Create.*\.md)|(Update.*\.md))/

version: 1.0.{build}

configuration: Release

environment:
  sourcesFolder: src
  solutionName: photosphere-mapping.sln
  projectName: Photosphere.Mapping

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - cd sourcesFolder
  - nuget restore
  - cd ..
  - ps: $nuspec = [xml](Get-Content .\$env:sourcesFolder\$env:projectName\$env:projectName.nuspec)
  - ps: $nuspec.package.metadata.version = $env:APPVEYOR_BUILD_VERSION
  - ps: $nuspec.Save()

build:
  verbosity: minimal  
  project: $(sourcesFolder)\$(solutionName)
  publish_nuget: true
  publish_nuget_symbols: true

artifacts:
  - path: $(sourcesFolder)\$(projectName)\bin\$(configuration)\
    name: $(projectName)-$(APPVEYOR_BUILD_VERSION)
