skip_commits:
  message: /((Create.*\.md)|(Update.*\.md))/

version: 1.0.{build}

configuration: Release

before_build:
  - cd src
  - nuget restore
  - cd ..

build:
  verbosity: minimal  
  project: src\photosphere-mapping.sln
  publish_nuget: true
  publish_nuget_symbols: true

artifacts:
  - path: src\Photosphere.Mappings\bin\$(configuration)\
    name: Photospere.Mapping-{version}
