skip_commits:
  message: /((Create.*\.md)|(Update.*\.md))/

version: 1.0.{build}

configuration: Release

environment:
  solutionPath: src\photosphere-mapping.sln
  projectName: Photosphere.Mapping
  projectPath: src\$(projectName)
  nuspecPath: $(projectPath)\$(projectName).nuspec

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - cd src
  - nuget restore
  - cd ..
  - ps:
    $nuspec = [xml](Get-Content .\$env:nuspecPath)
    $nuspec.package.metadata.version = $env:APPVEYOR_BUILD_VERSION
    $nuspec.Save()

build:
  verbosity: minimal  
  project: $(solutionPath)
  publish_nuget: true
  publish_nuget_symbols: true

artifacts:
  - path: $(projectPath)\bin\$(configuration)\
    name: $(projectName)
